name: zerosky
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.31.18
  camera: ^0.11.0
  geolocator: ^12.0.0
  path_provider: ^2.1.2
  path: ^1.9.0
  # Poseidonハッシュ計算のためのライブラリ
  poseidon: ^0.0.1
  # エクスポート機能のために追加
  share_plus: ^12.0.1
  # UIで使うアイコン
  cupertino_icons: ^1.0.2
  http: ^1.4.0
  intl: ^0.20.2
  location: ^8.0.1
  safe_device: ^1.3.5
  shamir_secret_plg: ^0.5.0
  webview_flutter: ^4.8.0
  flutter_inappwebview: ^6.1.5
  flutter_secure_storage: ^9.2.4
  web3dart: ^2.7.3
  url_launcher: ^6.3.2
  ethers: ^0.0.1+3
  sqflite: ^2.3.0

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1


dependency_overrides:
  http: ^1.2.0 # httpの最新の1.x系バージョンを指定

flutter:
  uses-material-design: true
  assets:

    - assets/
    - assets/cert.pem
    - assets/web/mpc_client.html
    - assets/abi/



flutter_launcher_icons:

  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # for adaptive icons


